r199: Add -u flag, shell portability, intelligently default SPN additions.
The -u flag allows the script to pass -u to vastool when needed.
Otherwise "-u HTTP/" is used where possible, thus allowing for re-use of
the keytab for low privilege queries. If -u is not provided, then the existing
krb5cc is used, or kinit is called.

Binary AND and OR functions are supplied for where $((..)) syntax is
unavailable.

When prompting for SPNs to add, use the samAccountName$ of host/ to determine
the alias "HTTP/<samAccountName>" and set that as the initial default when
adding aliases.

diff --git a/setup-mod_auth_vas.in b/setup-mod_auth_vas.in
--- a/setup-mod_auth_vas.in
+++ b/setup-mod_auth_vas.in
@@ -88,9 +88,9 @@ recordcmd () {
 
 #-- get a TGT for some operations
 kinit () {
-    if [ "z$KRB5CCNAME" != "z" ]; then
-	# Not checking whether the file is readable. If you want to do that,
-	# be sure to strip the possible preceding "FILE:"
+    if [ -n "$KRB5CCNAME" -o -n "$uflag" ]; then
+	# If KRB5CCNAME is exported, then assume kinit is done
+	# If -u is supplied then a password will be prompted
 	return
     fi
     if test -r /tmp/krb5cc_`id -u`; then
@@ -114,7 +114,7 @@ kinit () {
         query "Username" USER ${USER}
 	KRB5CCNAME=FILE:$ccname; export KRB5CCNAME
 	trap "rm -f $ccname" 0
-	$VASTOOL kinit "$USER" || die "Unable to acquire admin credentials"
+	$VASTOOL kinit "$USER" || die "Unable to acquire credentials"
     fi
 }
 
@@ -130,6 +130,8 @@ usage () {
 	          not specified, the apxs extension tool is queried.
 	    -h
 	          Display this help text.
+	    -u user
+		  Specify a user to create the service keytab
 .
 }
 
@@ -156,6 +158,7 @@ determine_keytab_access () {
 
 cflag=
 aflag=
+unset uflag
 opterr=false
 
 while test $# -gt 0; do
@@ -173,6 +176,11 @@ while test $# -gt 0; do
 	     fi;;
 	-a*) aflag=`echo " $1" | sed -e 's/^ -a//'`; shift;;
 	-h)  usage; exit 0;;
+	-u)  if test $# -lt 2; then 
+		echo "Missing argument to $1"; opterr=true; shift
+	     else
+		uflag="$2"; shift; shift
+	     fi;;
 	--)  shift; break;;
 	-?*) echo "Unknown option: $1"; opterr=true; shift;;
 	*)   break;;
@@ -331,6 +339,7 @@ if [ $keytab_exists = no ]; then
 	kinit "create the service account"
 
         recordcmd $VASTOOL \
+	    ${uflag+-u "$uflag"} \
 	    service create ${CONTAINER:+-c "$CONTAINER"} HTTP/ || \
 	    die "Cannot create HTTP/ service key: contact your IT support"
 
@@ -430,12 +439,21 @@ SPN aliases can also be useful for servers with multiple DNS identities.
 if test "$keytab_readable" = "no"; then
     echo >&2
     echo "Keytab is not readable. Skipping Service Principal Name (SPN) aliasing." >&2
-    echo "Re-run $0 as root to do SPN aliasing." >&2
+    echo "Re-run $0 as root to set up SPN aliasing." >&2
     echo >&2
 else
     kinit "run tests on the service account"
-    spns=`$VASTOOL attrs -s HTTP/ servicePrincipalName | wc -l`
+    spns=`$VASTOOL -u HTTP/ attrs -s HTTP/ servicePrincipalName | wc -l`
     primary=`$KTUTIL -k "$KEYTAB" list 2> /dev/null | awk 'NR==4 {print $3}'`
+
+    #-- change the default to a suggested short spn
+    default_spn=none
+    if test 1 -eq "$spns"; then
+	nbname=`$VASTOOL -u HTTP/ attrs -s host/ sAMAccountName | sed -e 's/^.*: //;s/\$$//'`
+	if test x"HTTP/$nbname" != x"`$VASTOOL -u HTTP/ attrs -s HTTP/ servicePrincipalName | sed -e 's/.*: //'`"; then
+	    default_spn="HTTP/$nbname"
+	fi
+    fi
 
     while :; do
 	    cat <<.
@@ -443,54 +461,61 @@ else
 The HTTP/ service is currently known by these SPNs (service principal names):
 
 .
-	    $VASTOOL attrs -s HTTP/ servicePrincipalName | 
+	    $VASTOOL -u HTTP/ attrs -s HTTP/ servicePrincipalName | 
 		awk '{print "\t" $2 }'
 	    echo
-	    query "Enter a new SPN alias, or 'none' to finish" SPN "none"
+	    query "Enter a new SPN alias, or 'none' to finish" SPN "$default_spn"
 	    [ x"$SPN" = x"none" ] && break
 
 	    case "$SPN" in
 		-*)
 		    newspns=
 		    found=false
-		    for spn in `$VASTOOL attrs -s HTTP/ servicePrincipalName | 
+		    for spn in `$VASTOOL -u HTTP/ attrs -s HTTP/ servicePrincipalName | 
 			awk '{print $2}'`; do
 			if [ x"-$spn" = x"$SPN" ]; then found=true
 			else newspns="$newspns $spn"; fi
 		    done
 		    if $found; then
-			$VASTOOL setattrs -m -s HTTP/ servicePrincipalName \
+			recordcmd $VASTOOL ${uflag+-u "$uflag"} \
+			    setattrs -m -s HTTP/ servicePrincipalName \
 			    $newspns 
-			$VASTOOL ktutil -k /etc/opt/quest/vas/HTTP.keytab \
+			recordcmd $VASTOOL ktutil -k /etc/opt/quest/vas/HTTP.keytab \
 			    remove -p ${SPN#-}
 		    else
 			echo "'${SPN#-}' not found" >&2
 		    fi
 		    ;;
 		*)
-		    oldspns=`$VASTOOL attrs -s HTTP/ servicePrincipalName | 
+		    oldspns=`$VASTOOL -u HTTP/ attrs -s HTTP/ servicePrincipalName | 
 			awk '{print $2}'`
-		    $VASTOOL setattrs -m -s HTTP/ servicePrincipalName \
-			$oldspns $SPN &&\
-		    $VASTOOL ktutil -k /etc/opt/quest/vas/HTTP.keytab \
-			alias $primary $SPN
+		    recordcmd $VASTOOL ${uflag+-u "$uflag"} \
+			    setattrs -m -s HTTP/ servicePrincipalName \
+			    $oldspns $SPN &&\
+		    recordcmd $VASTOOL ktutil -k /etc/opt/quest/vas/HTTP.keytab \
+			    alias $primary $SPN
 		    ;;
 	    esac
+	    default_spn=none
     done
 fi
+
+#-- Bitwise operators (decimal integers only)
+binary_or () { awk 'END { c = 0; for (i = 1; a || b; i *= 2) { a0 = a%2; b0 = b%2; if (a0 || b0) c += i; a = (a-a0)/2; b = (b-b0)/2; } print c; }' a="$1" b="$2" < /dev/null ; }
+binary_and () { awk 'END { c = 0; for (i = 1; a && b; i *= 2) { a0 = a%2; b0 = b%2; if (a0 && b0) c += i; a = (a-a0)/2; b = (b-b0)/2; } print c; }' a="$1" b="$2" < /dev/null ; }
 
 # Bug 213: HTTP/ keytab will expire by default
 if test -f "$KEYTAB"; then
     kinit "check that the service account is usable"
     label Testing whether service password expires
     # vastool attrs '-q' flag was only added in 3.2, so use sed magic.
-    uac=`$VASTOOL attrs HTTP/ userAccountControl | sed -e 's,userAccountControl: \([0-9]*\),\1,'`
+    uac=`$VASTOOL -u HTTP/ attrs HTTP/ userAccountControl | sed -e 's,userAccountControl: \([0-9]*\),\1,'`
     if [ "z$uac" = "z" ]; then
 	die "Unable to retrieve service account attributes, does the service exist?\
  Delete $KEYTAB and re-run $0 to re-create the service account."
     fi
     noexpire_flag=65536 # "Password never expires" (KB305144)
-    if test $(($uac & $noexpire_flag)) -eq 0; then
+    if test `binary_and $uac $noexpire_flag` -eq 0; then
 	echo yes
 	echo >&2
 	cat <<-. >&2
@@ -499,7 +524,9 @@ if test -f "$KEYTAB"; then
 	failures.
 .
 	if yesorno "Disable password expiry for the service account? (recommended)"; then
-	    recordcmd $VASTOOL setattrs -s HTTP/ userAccountControl $(($uac | $noexpire_flag))
+	    recordcmd $VASTOOL ${uflag+-u "$uflag"} \
+		setattrs -s HTTP/ userAccountControl \
+				  `binary_or $uac $noexpire_flag`
 	    echo
 	fi
     else
